packages:
  - "apps/*"
  - "apps/firebase/functions"
  - "packages/*"
  - "enterprise/*"

onlyBuiltDependencies:
  - "esbuild"
  - "sharp"
  - "bcrypt"
  - "protobufjs"
  - "chromedriver"
  - "@firebase/util"
  - "re2"
