import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { WebviewWindow } from "@tauri-apps/api/webviewWindow";
import { createId } from "./id.utils";

export type ComposerResult = {
  requestId: string;
  accepted: boolean;
  text: string;
};

const COMPOSER_TIMEOUT_MS = 5 * 60 * 1000;
const BASE64_CHUNK_SIZE = 0x8000;

/**
 * Encode transcript text with a URL-safe alphabet. The Rust floating-route
 * validator must reject path traversal, but transcript content is arbitrary
 * user data and may legitimately contain `..` (for example, "Wait... what?").
 */
export const encodeComposerText = (text: string): string => {
  const bytes = new TextEncoder().encode(text);
  let binary = "";
  for (let offset = 0; offset < bytes.length; offset += BASE64_CHUNK_SIZE) {
    binary += String.fromCharCode(
      ...bytes.subarray(offset, offset + BASE64_CHUNK_SIZE),
    );
  }

  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/u, "");
};

/** Decode the URL-safe transcript payload used by the local composer route. */
export const decodeComposerText = (encoded: string): string => {
  try {
    const padded = encoded.replace(/-/g, "+").replace(/_/g, "/");
    const base64 = padded + "=".repeat((4 - (padded.length % 4)) % 4);
    const binary = atob(base64);
    const bytes = Uint8Array.from(binary, (character) =>
      character.charCodeAt(0),
    );
    return new TextDecoder().decode(bytes);
  } catch {
    // Keep routes generated by older builds usable during an update/rollback.
    return encoded;
  }
};

/** Open the local composer popout and wait for its Insert/Cancel decision. */
export const reviewTextInComposer = async (
  text: string,
): Promise<string | null> => {
  const requestId = createId();
  const route = `composer?requestId=${encodeURIComponent(requestId)}&text64=${encodeURIComponent(encodeComposerText(text))}`;
  let windowId: string | null = null;
  let unlisten: (() => void) | undefined;
  let unlistenClose: (() => void) | undefined;

  try {
    const result = await new Promise<string | null>((resolve, reject) => {
      let settled = false;
      let timeoutId: number | null = null;
      const finish = (value: string | null) => {
        if (settled) return;
        settled = true;
        if (timeoutId !== null) {
          window.clearTimeout(timeoutId);
          timeoutId = null;
        }
        resolve(value);
      };

      void (async () => {
        try {
          unlisten = await listen<ComposerResult>(
            "composer-result",
            (event) => {
              if (event.payload.requestId !== requestId) return;
              finish(event.payload.accepted ? event.payload.text : null);
            },
          );

          const created = await invoke<{ id: string }>(
            "floating_window_create",
            {
              args: {
                url: "about:blank",
                route,
                title: "Review transcript",
                width: 560,
                height: 420,
                minWidth: 360,
                minHeight: 280,
                decorations: true,
                resizable: true,
                focused: true,
              },
            },
          );
          windowId = created.id;

          // A user closing the popout is a Cancel decision. Without this
          // listener the caller waits for the five-minute timeout and keeps
          // the dictation/paste flow blocked.
          const composerWindow = await WebviewWindow.getByLabel(created.id);
          if (composerWindow) {
            unlistenClose = await composerWindow.onCloseRequested(() => {
              finish(null);
            });
          }

          timeoutId = window.setTimeout(() => {
            finish(null);
          }, COMPOSER_TIMEOUT_MS);
        } catch (error) {
          reject(error);
        }
      })();
    });
    return result;
  } finally {
    unlisten?.();
    unlistenClose?.();
    if (windowId) {
      await invoke("floating_window_destroy", { id: windowId }).catch(() => {
        // The user may already have closed the popout.
      });
    }
  }
};
